steps:
  - name: node:12.22.5
    entrypoint: yarn
    args: ['install']
  - name: node:12.22.5
    entrypoint: yarn
    args: ['run', 'build']
    env:
      # API
      - VUE_APP_API_BASE_URL=https://api.achilio.com
      # Authentication
      - VUE_APP_AUTH_BASE_URL=https://auth.achilio.com
      - VUE_APP_GOOGLE_OAUTH2_URL=https://accounts.google.com/o/oauth2/v2/auth
      - VUE_APP_GOOGLE_OAUTH2_CLIENT_ID=293325499254-8h7bv5piflnjdoufjak8jjh03tpqss8b.apps.googleusercontent.com
      - VUE_APP_SERVER_AUTH_REDIRECT=api/v1/auth/login/google/
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['app', 'deploy']
