steps:
  - name: node:12.22.5
    entrypoint: yarn
    args: ["install"]
  - name: node:12.22.5
    entrypoint: yarn
    args: ["run", "build"]
    env:
      - VUE_APP_API_BASE_URL=https://api.achilio.com
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy"]
